services:
  crongen:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crongen-app
    restart: unless-stopped
        networks:
            - backbone

networks:
    backbone:
        external: true